using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace YuGiOh_DeckBuilder.YuGiOh.Enums.Utility;

internal static partial class Translator
{
    #region Properties
    /// <summary>
    /// Contains <see cref="MonsterType"/> translations for every <see cref="Language"/> <br/>
    /// https://yugioh.fandom.com/wiki/Type
    /// </summary>
    internal static ReadOnlyDictionary<Language, IDictionary<MonsterType, string>> MonsterTypes { get; } = new
    (
        new Dictionary<Language, IDictionary<MonsterType, string>>
        {
            {
                Language.en, new Dictionary<MonsterType, string>
                {
                    { MonsterType.Normal, "Normal" },
                    { MonsterType.Aqua, "Aqua" },
                    { MonsterType.Beast, "Beast" },
                    { MonsterType.BeastWarrior, "Beast-Warrior" },
                    { MonsterType.CreatorGod, "Creator God" },
                    { MonsterType.Cyberse, "Cyberse" },
                    { MonsterType.Dinosaur, "Dinosaur" },
                    { MonsterType.DivineBeast, "Divine-Beast" },
                    { MonsterType.Dragon, "Dragon" },
                    { MonsterType.Effect, "Effect" },
                    { MonsterType.Fairy, "Fairy" },
                    { MonsterType.Fiend, "Fiend" },
                    { MonsterType.Fish, "Fish" },
                    { MonsterType.Flip, "Flip" },
                    { MonsterType.Fusion, "Fusion" },
                    { MonsterType.Gemini, "Gemini" },
                    { MonsterType.Insect, "Insect" },
                    { MonsterType.Link, "Link" },
                    { MonsterType.Machine, "Machine" },
                    { MonsterType.Pendulum, "Pendulum" },
                    { MonsterType.Plant, "Plant" },
                    { MonsterType.Psychic, "Psychic" },
                    { MonsterType.Pyro, "Pyro" },
                    { MonsterType.Reptile, "Reptile" },
                    { MonsterType.Ritual, "Ritual" },
                    { MonsterType.Rock, "Rock" },
                    { MonsterType.SeaSerpent, "Sea Serpent" },
                    { MonsterType.Spellcaster, "Spellcaster" },
                    { MonsterType.Spirit, "Spirit" },
                    { MonsterType.Synchro, "Synchro" },
                    { MonsterType.Thunder, "Thunder" },
                    { MonsterType.Toon, "Toon" },
                    { MonsterType.Tuner, "Tuner" },
                    { MonsterType.Union, "Union" },
                    { MonsterType.Warrior, "Warrior" },
                    { MonsterType.WingedBeast, "Winged Beast" },
                    { MonsterType.Wyrm, "Wyrm" },
                    { MonsterType.Xyz, "Xyz" },
                    { MonsterType.Zombie, "Zombie" }
                }
            },
            {
                Language.de, new Dictionary<MonsterType, string>
                {
                    { MonsterType.Normal, "Normal" },
                    { MonsterType.Aqua, "Aqua" },
                    { MonsterType.Beast, "Ungeheuer" },
                    { MonsterType.BeastWarrior, "Ungeheuer-Krieger" },
                    { MonsterType.CreatorGod, "Schöpfer Gott" },
                    { MonsterType.Cyberse, "Cyberse" },
                    { MonsterType.Dinosaur, "Dinosaurier" },
                    { MonsterType.DivineBeast, "Göttliches Ungeheuer" },
                    { MonsterType.Dragon, "Drache" },
                    { MonsterType.Effect, "Effekt" },
                    { MonsterType.Fairy, "Fee" },
                    { MonsterType.Fiend, "Unterweltler" },
                    { MonsterType.Fish, "Fisch" },
                    { MonsterType.Flip, "Flipp" },
                    { MonsterType.Fusion, "Fusion" },
                    { MonsterType.Gemini, "Zwilling" },
                    { MonsterType.Insect, "Insekt" },
                    { MonsterType.Link, "Link" },
                    { MonsterType.Machine, "Maschine" },
                    { MonsterType.Pendulum, "Pendel" },
                    { MonsterType.Plant, "Pflanze" },
                    { MonsterType.Psychic, "Psi" },
                    { MonsterType.Pyro, "Pyro" },
                    { MonsterType.Reptile, "Reptil" },
                    { MonsterType.Ritual, "Ritual" },
                    { MonsterType.Rock, "Fels" },
                    { MonsterType.SeaSerpent, "Seeschlange" },
                    { MonsterType.Spellcaster, "Hexer" },
                    { MonsterType.Spirit, "Spirit" },
                    { MonsterType.Synchro, "Synchro" },
                    { MonsterType.Thunder, "Donner" },
                    { MonsterType.Toon, "Toon" },
                    { MonsterType.Tuner, "Empfänger" },
                    { MonsterType.Union, "Union" },
                    { MonsterType.Warrior, "Krieger" },
                    { MonsterType.WingedBeast, "Geflügeltes Ungeheuer" },
                    { MonsterType.Wyrm, "Wyrm" },
                    { MonsterType.Xyz, "Xyz" },
                    { MonsterType.Zombie, "Zombie" }
                }
            },
            {
                Language.es, new Dictionary<MonsterType, string>
                {
                    { MonsterType.Normal, "Normal" },
                    { MonsterType.Aqua, "Aqua" },
                    { MonsterType.Beast, "Bestia" },
                    { MonsterType.BeastWarrior, "Guerrero-Bestia" },
                    { MonsterType.CreatorGod, "Dios creador" },
                    { MonsterType.Cyberse, "Ciberso" },
                    { MonsterType.Dinosaur, "Dinosaurio" },
                    { MonsterType.DivineBeast, "Bestia Divina" },
                    { MonsterType.Dragon, "Dragón" },
                    { MonsterType.Effect, "Efecto" },
                    { MonsterType.Fairy, "Hada" },
                    { MonsterType.Fiend, "Demonio" },
                    { MonsterType.Fish, "Pez" },
                    { MonsterType.Flip, "Volteo" },
                    { MonsterType.Fusion, "Fusión" },
                    { MonsterType.Gemini, "Géminis" },
                    { MonsterType.Insect, "Insecto" },
                    { MonsterType.Link, "Enlace" },
                    { MonsterType.Machine, "Máquina" },
                    { MonsterType.Pendulum, "Péndulo" },
                    { MonsterType.Plant, "Planta" },
                    { MonsterType.Psychic, "Psíquico" },
                    { MonsterType.Pyro, "Piro" },
                    { MonsterType.Reptile, "Reptil" },
                    { MonsterType.Ritual, "Ritual" },
                    { MonsterType.Rock, "Roca" },
                    { MonsterType.SeaSerpent, "Serpiente Marina" },
                    { MonsterType.Spellcaster, "Lanzador de Conjuros" },
                    { MonsterType.Spirit, "Spirit" },
                    { MonsterType.Synchro, "Sincronía" },
                    { MonsterType.Thunder, "Trueno" },
                    { MonsterType.Toon, "Toon" },
                    { MonsterType.Tuner, "Cantante" },
                    { MonsterType.Union, "Unión" },
                    { MonsterType.Warrior, "Guerrero" },
                    { MonsterType.WingedBeast, "Bestia Alada" },
                    { MonsterType.Wyrm, "Wyrm" },
                    { MonsterType.Xyz, "Xyz" },
                    { MonsterType.Zombie, "Zombi" }
                }
            },
            {
                Language.fr, new Dictionary<MonsterType, string>
                {
                    { MonsterType.Normal, "Normal" },
                    { MonsterType.Aqua, "Aqua" },
                    { MonsterType.Beast, "Bête" },
                    { MonsterType.BeastWarrior, "Bête-Guerrier" },
                    { MonsterType.CreatorGod, "Dieu créateur" },
                    { MonsterType.Cyberse, "Cyberse" },
                    { MonsterType.Dinosaur, "Dinosaure" },
                    { MonsterType.DivineBeast, "Bête Divine" },
                    { MonsterType.Dragon, "Dragon" },
                    { MonsterType.Effect, "Effet" },
                    { MonsterType.Fairy, "Elfe" },
                    { MonsterType.Fiend, "Démon" },
                    { MonsterType.Fish, "Poisson" },
                    { MonsterType.Flip, "Flip" },
                    { MonsterType.Fusion, "Fusion" },
                    { MonsterType.Gemini, "Gémeau" },
                    { MonsterType.Insect, "Insecte" },
                    { MonsterType.Link, "Lien" },
                    { MonsterType.Machine, "Machine" },
                    { MonsterType.Pendulum, "Pendule" },
                    { MonsterType.Plant, "Plante" },
                    { MonsterType.Psychic, "Psychique" },
                    { MonsterType.Pyro, "Pyro" },
                    { MonsterType.Reptile, "Reptile" },
                    { MonsterType.Ritual, "Rituel" },
                    { MonsterType.Rock, "Rocher" },
                    { MonsterType.SeaSerpent, "Serpent de Mer" },
                    { MonsterType.Spellcaster, "Magicien" },
                    { MonsterType.Spirit, "Spirit" },
                    { MonsterType.Synchro, "Synchro" },
                    { MonsterType.Thunder, "Tonnerre" },
                    { MonsterType.Toon, "Toon" },
                    { MonsterType.Tuner, "Syntoniseur" },
                    { MonsterType.Union, "Union" },
                    { MonsterType.Warrior, "Guerrier" },
                    { MonsterType.WingedBeast, "Bête Ailée" },
                    { MonsterType.Wyrm, "Wyrm" },
                    { MonsterType.Xyz, "Xyz" },
                    { MonsterType.Zombie, "Zombie" }
                }
            },
            {
                Language.it, new Dictionary<MonsterType, string>
                {
                    { MonsterType.Normal, "Normale" },
                    { MonsterType.Aqua, "Acqua" },
                    { MonsterType.Beast, "Bestia" },
                    { MonsterType.BeastWarrior, "Guerriero-Bestia" },
                    { MonsterType.CreatorGod, "Dio Creatore" },
                    { MonsterType.Cyberse, "Cyberse" },
                    { MonsterType.Dinosaur, "Dinosauro" },
                    { MonsterType.DivineBeast, "Divinità-Bestia" },
                    { MonsterType.Dragon, "Drago" },
                    { MonsterType.Effect, "Effetto" },
                    { MonsterType.Fairy, "Fata" },
                    { MonsterType.Fiend, "Demone" },
                    { MonsterType.Fish, "Pesce" },
                    { MonsterType.Flip, "Scoperta" },
                    { MonsterType.Fusion, "Fusione" },
                    { MonsterType.Gemini, "Gemello" },
                    { MonsterType.Insect, "Insetto" },
                    { MonsterType.Link, "Link" },
                    { MonsterType.Machine, "Macchina" },
                    { MonsterType.Pendulum, "Pendulum" },
                    { MonsterType.Plant, "Pianta" },
                    { MonsterType.Psychic, "Psichico" },
                    { MonsterType.Pyro, "Pyro" },
                    { MonsterType.Reptile, "Rettile" },
                    { MonsterType.Ritual, "Rituale" },
                    { MonsterType.Rock, "Roccia" },
                    { MonsterType.SeaSerpent, "Serpente Marino" },
                    { MonsterType.Spellcaster, "Incantatore" },
                    { MonsterType.Spirit, "Spirit" },
                    { MonsterType.Synchro, "Synchro" },
                    { MonsterType.Thunder, "Tuono" },
                    { MonsterType.Toon, "Toon" },
                    { MonsterType.Tuner, "Tuner" },
                    { MonsterType.Union, "Unione" },
                    { MonsterType.Warrior, "Guerriero" },
                    { MonsterType.WingedBeast, "Bestia Alata" },
                    { MonsterType.Wyrm, "Wyrm" },
                    { MonsterType.Xyz, "Xyz" },
                    { MonsterType.Zombie, "Zombie" }
                }
            },
            {
                Language.ja, new Dictionary<MonsterType, string>
                {
                    { MonsterType.Normal, "通常" },
                    { MonsterType.Aqua, "水族" },
                    { MonsterType.Beast, "獣族" },
                    { MonsterType.BeastWarrior, "獣戦士族" },
                    { MonsterType.CreatorGod, "創造神" },
                    { MonsterType.Cyberse, "サイバース族" },
                    { MonsterType.Dinosaur, "恐竜族" },
                    { MonsterType.DivineBeast, "幻神獣族" },
                    { MonsterType.Dragon, "ドラゴン族" },
                    { MonsterType.Effect, "効果" },
                    { MonsterType.Fairy, "天使族" },
                    { MonsterType.Fiend, "悪魔族" },
                    { MonsterType.Fish, "魚族" },
                    { MonsterType.Flip, "リバース" },
                    { MonsterType.Fusion, "融合" },
                    { MonsterType.Gemini, "デュアル" },
                    { MonsterType.Insect, "昆虫族" },
                    { MonsterType.Link, "リンク" },
                    { MonsterType.Machine, "機械族" },
                    { MonsterType.Pendulum, "ペンデュラム" },
                    { MonsterType.Plant, "植物族" },
                    { MonsterType.Psychic, "サイキック族" },
                    { MonsterType.Pyro, "炎族" },
                    { MonsterType.Reptile, "爬虫類族" },
                    { MonsterType.Ritual, "儀式" },
                    { MonsterType.Rock, "岩石族" },
                    { MonsterType.SeaSerpent, "海竜族" },
                    { MonsterType.Spellcaster, "魔法使い族" },
                    { MonsterType.Spirit, "スピリット" },
                    { MonsterType.Synchro, "シンクロ" },
                    { MonsterType.Thunder, "雷族" },
                    { MonsterType.Toon, "トゥーン" },
                    { MonsterType.Tuner, "チューナー" },
                    { MonsterType.Union, "ユニオン" },
                    { MonsterType.Warrior, "戦士族" },
                    { MonsterType.WingedBeast, "鳥獣族" },
                    { MonsterType.Wyrm, "幻竜族" },
                    { MonsterType.Xyz, "エクシーズ" },
                    { MonsterType.Zombie, "アンデット族" }
                }
            },
            {
                Language.ko, new Dictionary<MonsterType, string>
                {
                    { MonsterType.Normal, "일반" },
                    { MonsterType.Aqua, "물족" },
                    { MonsterType.Beast, "야수족" },
                    { MonsterType.BeastWarrior, "야수전사족" },
                    { MonsterType.CreatorGod, "창조주 하나님" },
                    { MonsterType.Cyberse, "사이버스족" },
                    { MonsterType.Dinosaur, "공룡족" },
                    { MonsterType.DivineBeast, "환신야수족" },
                    { MonsterType.Dragon, "드래곤족" },
                    { MonsterType.Effect, "효과" },
                    { MonsterType.Fairy, "천사족" },
                    { MonsterType.Fiend, "악마족" },
                    { MonsterType.Fish, "어류족" },
                    { MonsterType.Flip, "리버스" },
                    { MonsterType.Fusion, "융합" },
                    { MonsterType.Gemini, "듀얼" },
                    { MonsterType.Insect, "곤충족" },
                    { MonsterType.Link, "링크" },
                    { MonsterType.Machine, "기계족" },
                    { MonsterType.Pendulum, "펜듈럼" },
                    { MonsterType.Plant, "식물족" },
                    { MonsterType.Psychic, "사이킥족" },
                    { MonsterType.Pyro, "화염족" },
                    { MonsterType.Reptile, "파충류족" },
                    { MonsterType.Ritual, "의식" },
                    { MonsterType.Rock, "암석족" },
                    { MonsterType.SeaSerpent, "해룡족" },
                    { MonsterType.Spellcaster, "마법사족" },
                    { MonsterType.Spirit, "스피릿" },
                    { MonsterType.Synchro, "싱크로" },
                    { MonsterType.Thunder, "번개족" },
                    { MonsterType.Toon, "툰" },
                    { MonsterType.Tuner, "튜너" },
                    { MonsterType.Union, "유니온" },
                    { MonsterType.Warrior, "전사족" },
                    { MonsterType.WingedBeast, "비행야수족" },
                    { MonsterType.Wyrm, "환룡족" },
                    { MonsterType.Xyz, "엑시즈" },
                    { MonsterType.Zombie, "언데드족" }
                }
            },
            {
                Language.pt, new Dictionary<MonsterType, string>
                {
                    { MonsterType.Normal, "Normal" },
                    { MonsterType.Aqua, "Aqua" },
                    { MonsterType.Beast, "Besta" },
                    { MonsterType.BeastWarrior, "Besta-Guerreira" },
                    { MonsterType.CreatorGod, "Deus Criador" },
                    { MonsterType.Cyberse, "Ciberso" },
                    { MonsterType.Dinosaur, "Dinossauro" },
                    { MonsterType.DivineBeast, "Besta Divina" },
                    { MonsterType.Dragon, "Dragão" },
                    { MonsterType.Effect, "Efeito" },
                    { MonsterType.Fairy, "Fada" },
                    { MonsterType.Fiend, "Demônio" },
                    { MonsterType.Fish, "Peixe" },
                    { MonsterType.Flip, "Virar" },
                    { MonsterType.Fusion, "Fusão" },
                    { MonsterType.Gemini, "Gêmeos" },
                    { MonsterType.Insect, "Inseto" },
                    { MonsterType.Link, "Link" },
                    { MonsterType.Machine, "Máquina" },
                    { MonsterType.Pendulum, "Pêndulo" },
                    { MonsterType.Plant, "Planta" },
                    { MonsterType.Psychic, "Psíquico" },
                    { MonsterType.Pyro, "Piro" },
                    { MonsterType.Reptile, "Réptil" },
                    { MonsterType.Ritual, "Ritual" },
                    { MonsterType.Rock, "Rocha" },
                    { MonsterType.SeaSerpent, "Serpente Marinha" },
                    { MonsterType.Spellcaster, "Mago" },
                    { MonsterType.Spirit, "Espírito" },
                    { MonsterType.Synchro, "Sincro" },
                    { MonsterType.Thunder, "Trovão" },
                    { MonsterType.Toon, "Toon" },
                    { MonsterType.Tuner, "Regulador" },
                    { MonsterType.Union, "Union" },
                    { MonsterType.Warrior, "Guerreiro" },
                    { MonsterType.WingedBeast, "Besta Alada" },
                    { MonsterType.Wyrm, "Wyrm" },
                    { MonsterType.Xyz, "Xyz" },
                    { MonsterType.Zombie, "Zumbi" }
                }
            },
            {
                Language.zh, new Dictionary<MonsterType, string>
                {
                    { MonsterType.Normal, "普通的" },
                    { MonsterType.Aqua, "水族" },
                    { MonsterType.Beast, "兽" },
                    { MonsterType.BeastWarrior, "野兽战士" },
                    { MonsterType.CreatorGod, "造物主" },
                    { MonsterType.Cyberse, "网络版" },
                    { MonsterType.Dinosaur, "恐龙" },
                    { MonsterType.DivineBeast, "神兽" },
                    { MonsterType.Dragon, "龙" },
                    { MonsterType.Effect, "影响" },
                    { MonsterType.Fairy, "仙女" },
                    { MonsterType.Fiend, "恶魔" },
                    { MonsterType.Fish, "鱼" },
                    { MonsterType.Flip, "翻动" },
                    { MonsterType.Fusion, "融合" },
                    { MonsterType.Gemini, "双子座" },
                    { MonsterType.Insect, "昆虫" },
                    { MonsterType.Link, "关联" },
                    { MonsterType.Machine, "机器" },
                    { MonsterType.Pendulum, "摆" },
                    { MonsterType.Plant, "植物" },
                    { MonsterType.Psychic, "精神" },
                    { MonsterType.Pyro, "火焰兵" },
                    { MonsterType.Reptile, "爬虫" },
                    { MonsterType.Ritual, "仪式" },
                    { MonsterType.Rock, "岩石" },
                    { MonsterType.SeaSerpent, "海蛇" },
                    { MonsterType.Spellcaster, "施法者" },
                    { MonsterType.Spirit, "精神" },
                    { MonsterType.Synchro, "同步" },
                    { MonsterType.Thunder, "雷" },
                    { MonsterType.Toon, "香椿" },
                    { MonsterType.Tuner, "调谐器" },
                    { MonsterType.Union, "联盟" },
                    { MonsterType.Warrior, "战士" },
                    { MonsterType.WingedBeast, "翼兽" },
                    { MonsterType.Wyrm, "蛟龙" },
                    { MonsterType.Xyz, "XYZ" },
                    { MonsterType.Zombie, "僵尸" }
                }
            },
        }
    );
    #endregion
}
