using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace YuGiOh_DeckBuilder.YuGiOh.Enums.Utility;

internal static partial class Translator
{
    #region Properties

    #endregion

    /// <summary>
    /// Contains <see cref="Rarity"/> translations for every <see cref="Language"/> <br/>
    /// https://yugioh.fandom.com/wiki/Rarity
    /// </summary>
    internal static ReadOnlyDictionary<Language, IDictionary<Rarity, string>> Rarities { get; } = new
    (
        new Dictionary<Language, IDictionary<Rarity, string>>
        {
            {
                Language.en, new Dictionary<Rarity, string>
                {
                    { Rarity.N, "Normal" },
                    { Rarity.C, "Common" },
                    { Rarity.NR, "Normal Rare" },
                    { Rarity.SP, "Short Print" },
                    { Rarity.SSP, "Super Short Print" },
                    { Rarity.HFR, "Holofoil Rare" },
                    { Rarity.R, "Rare" },
                    { Rarity.SR, "Super Rare" },
                    { Rarity.UR, "Ultra Rare" },
                    { Rarity.URPR, "Pharaoh's Rare" },
                    { Rarity.UtR, "Ultimate Rare" },
                    { Rarity.GR, "Ghost Rare" },
                    { Rarity.HGR, "Holographic Rare" },
                    { Rarity.PIR, "Platinum Rare" },
                    { Rarity.StR, "Starlight Rare" },
                    { Rarity.ScR, "Secret Rare" },
                    { Rarity.PScR, "Prismatic Secret Rare" },
                    { Rarity.EScR, "Extra Secret Rare" },
                    { Rarity.PlScR, "Platinum Secret Rare" },
                    { Rarity.UScR, "Ultra Secret Rare" },
                    { Rarity._20ScR, "20th Secret Rare" },
                    { Rarity.ScUR, "Secret Ultra Rare" },
                    { Rarity._10000ScR, "10000 Secret Rare" },
                    { Rarity.PR, "Parallel Rare" },
                    { Rarity.NPR, "Normal Parallel Rare" },
                    { Rarity.PC, "Parallel Common" },
                    { Rarity.SPR, "Super Parallel Rare" },
                    { Rarity.UPR, "Ultra Parallel Rare" },
                    { Rarity.ScPR, "Secret Parallel Rare" },
                    { Rarity.EScPR, "Extra Secret Parallel Rare" },
                    { Rarity.SFR, "Starfoil Rare" },
                    { Rarity.MSR, "Mosaic Rare" },
                    { Rarity.SHR, "Shatterfoil Rare" },
                    { Rarity.CR, "Collector's Rare" },
                    { Rarity.HGPR, "Holographic Parallel Rare" },
                    { Rarity.KCC, "Kaiba Corporation Common" },
                    { Rarity.KCR, "Kaiba Corporation Rare" },
                    { Rarity.KCUR, "Kaiba Corporation Ultra Rare" },
                    { Rarity.GUR, "Gold Rare" },
                    { Rarity.GScR, "Gold Secret Rare" },
                    { Rarity.GGR, "Ghost/Gold Rare" },
                    { Rarity.PGR, "Premium Gold Rare" },
                    { Rarity.MLR, "Millennium Rare" },
                    { Rarity.MLSR, "Millennium Super Rare" },
                    { Rarity.MLUR, "Millennium Ultra Rare" },
                    { Rarity.MLScR, "Millennium Secret Rare" },
                    { Rarity.MLGR, "Millennium Gold Rare" },
                    { Rarity.DNPR, "Duel Terminal Normal Parallel Rare" },
                    { Rarity.DPC, "Duel Terminal Parallel Common" },
                    { Rarity.DNRPR, "Duel Terminal Normal Rare Parallel Rare" },
                    { Rarity.DRPR, "Duel Terminal Rare Parallel Rare" },
                    { Rarity.DSPR, "Duel Terminal Super Parallel Rare" },
                    { Rarity.DUPR, "Duel Terminal Ultra Parallel Rare" },
                    { Rarity.DScPR, "Duel Terminal Secret Parallel Rare" },
                    { Rarity.RR, "Rush Rare" },
                    { Rarity.GRR, "Gold Rush Rare" },
                    { Rarity.ORR, "Over Rush Rare" },
                    { Rarity.SE, "Standard Edition" },
                    { Rarity._1E, "1st Edition" },
                    { Rarity.UE, "Unlimited Edition" },
                    { Rarity.LE, "Limited Edition" },
                    { Rarity.DT, "Duel Terminal Edition" },
                    { Rarity.FR, "Fixed Rarity" },
                    { Rarity.Vc, "Variant card" },
                    { Rarity.OgP, "Original Print" },
                    { Rarity.RP, "Replica" },
                    { Rarity.Rp, "Reprint" },
                    { Rarity.OoP, "Out of Print" },
                    { Rarity.GC, "Giant Card" },
                    { Rarity.OP, "Official Proxy" },
                    { Rarity.CT, "Case Topper" },
                    { Rarity.OSP, "Oversized Promo" },
                    { Rarity.BAM, "BAM Legend" }
                }
            },
            {
                Language.de, new Dictionary<Rarity, string>
                {
                    { Rarity.N, "Normal" },
                    { Rarity.C, "Verbreitet" },
                    { Rarity.NR, "Normal selten" },
                    { Rarity.SP, "Kurzdruck" },
                    { Rarity.SSP, "Super kurzer Druck" },
                    { Rarity.HFR, "Holofoil Selten" },
                    { Rarity.R, "Selten" },
                    { Rarity.SR, "Sehr selten" },
                    { Rarity.UR, "Ultra selten" },
                    { Rarity.URPR, "Pharao selten" },
                    { Rarity.UtR, "Ultimativ selten" },
                    { Rarity.GR, "Geist Selten" },
                    { Rarity.HGR, "Holographisch selten" },
                    { Rarity.PIR, "Platin Selten" },
                    { Rarity.StR, "Sternenlicht Selten" },
                    { Rarity.ScR, "Geheim selten" },
                    { Rarity.PScR, "Prismatisches Geheimnis Selten" },
                    { Rarity.EScR, "Extra geheim selten" },
                    { Rarity.PlScR, "Platinum Secret Selten" },
                    { Rarity.UScR, "Ultrageheim selten" },
                    { Rarity._20ScR, "20. Geheimnis Selten" },
                    { Rarity.ScUR, "Geheim Ultra Rare" },
                    { Rarity._10000ScR, "10000 geheim selten" },
                    { Rarity.PR, "Parallel Selten" },
                    { Rarity.NPR, "Normal Parallel Selten" },
                    { Rarity.PC, "Parallel verbreitet" },
                    { Rarity.SPR, "Superparallel Selten" },
                    { Rarity.UPR, "Ultraparallel Selten" },
                    { Rarity.ScPR, "Geheime Parallel Selten" },
                    { Rarity.EScPR, "Extra geheim Parallel selten" },
                    { Rarity.SFR, "Starfoil Selten" },
                    { Rarity.MSR, "Mosaik selten" },
                    { Rarity.SHR, "Splitterfolie Selten" },
                    { Rarity.CR, "Sammler selten" },
                    { Rarity.HGPR, "Holografische Parallele Selten" },
                    { Rarity.KCC, "Kaiba Corporation verbreitet" },
                    { Rarity.KCR, "Kaiba Corporation Selten" },
                    { Rarity.KCUR, "Kaiba Corporation Ultraselten" },
                    { Rarity.GUR, "Gold selten" },
                    { Rarity.GScR, "Seltenes Goldgeheimnis" },
                    { Rarity.GGR, "Geist/Gold Selten" },
                    { Rarity.PGR, "Premium-Gold selten" },
                    { Rarity.MLR, "Jahrtausend selten" },
                    { Rarity.MLSR, "Jahrtausend superselten" },
                    { Rarity.MLUR, "Jahrtausend extrem selten" },
                    { Rarity.MLScR, "Jahrtausendgeheimnis Selten" },
                    { Rarity.MLGR, "Millennium Gold selten" },
                    { Rarity.DNPR, "Duel Terminal Normal Parallel Selten" },
                    { Rarity.DPC, "Duel Terminal Parallel verbreitet" },
                    { Rarity.DNRPR, "Duell Terminal Normal Selten Parallel Selten" },
                    { Rarity.DRPR, "Duel Terminal selten Parallel selten" },
                    { Rarity.DSPR, "Duel Terminal Super Parallel Selten" },
                    { Rarity.DUPR, "Duel Terminal Ultra Parallel selten" },
                    { Rarity.DScPR, "Duel Terminal Secret Parallel selten" },
                    { Rarity.RR, "Rush Selten" },
                    { Rarity.GRR, "Goldrausch Selten" },
                    { Rarity.ORR, "Über Rush Rare" },
                    { Rarity.SE, "Standard Edition" },
                    { Rarity._1E, "1. Auflage" },
                    { Rarity.UE, "Unbegrenzte Ausgabe" },
                    { Rarity.LE, "Limitierte Auflage" },
                    { Rarity.DT, "Duel Terminal-Edition" },
                    { Rarity.FR, "Feste Seltenheit" },
                    { Rarity.Vc, "Variantenkarte" },
                    { Rarity.OgP, "Originaldruck" },
                    { Rarity.RP, "Replikat" },
                    { Rarity.Rp, "Nachdruck" },
                    { Rarity.OoP, "Nicht mehr im Druck" },
                    { Rarity.GC, "Riesige Karte" },
                    { Rarity.OP, "Offizieller Proxy" },
                    { Rarity.CT, "Koffer topper" },
                    { Rarity.OSP, "Übergroße Promo" },
                    { Rarity.BAM, "BAM-Legende" }
                }
            },
            {
                Language.es, new Dictionary<Rarity, string>
                {
                    { Rarity.N, "Normal" },
                    { Rarity.C, "Común" },
                    { Rarity.NR, "Rara normal" },
                    { Rarity.SP, "Impresión corta" },
                    { Rarity.SSP, "Estampado súper corto" },
                    { Rarity.HFR, "Holofoil rara" },
                    { Rarity.R, "Extraña" },
                    { Rarity.SR, "Super rara" },
                    { Rarity.UR, "Ultra raro" },
                    { Rarity.URPR, "Rara del faraón" },
                    { Rarity.UtR, "Última rara" },
                    { Rarity.GR, "Fantasma rara" },
                    { Rarity.HGR, "Rara holográfica" },
                    { Rarity.PIR, "Platino raro" },
                    { Rarity.StR, "Luz estelar rara" },
                    { Rarity.ScR, "Rara secreta" },
                    { Rarity.PScR, "Secreto Prismático Raro" },
                    { Rarity.EScR, "Extra secreta rara" },
                    { Rarity.PlScR, "Platino Secreto Raro" },
                    { Rarity.UScR, "Raro Ultra Secreto" },
                    { Rarity._20ScR, "20º Secreto Raro" },
                    { Rarity.ScUR, "Secreto ultra raro" },
                    { Rarity._10000ScR, "10000 Secreta Rara" },
                    { Rarity.PR, "Paralelo raro" },
                    { Rarity.NPR, "Rara paralela normal" },
                    { Rarity.PC, "Paralelo Común" },
                    { Rarity.SPR, "Super paralela rara" },
                    { Rarity.UPR, "Ultra Paralelo Raro" },
                    { Rarity.ScPR, "Secreto Paralelo Raro" },
                    { Rarity.EScPR, "Extra Secreto Paralelo Raro" },
                    { Rarity.SFR, "Starfoil rara" },
                    { Rarity.MSR, "Mosaica rara" },
                    { Rarity.SHR, "Shatterfoil rara" },
                    { Rarity.CR, "Raro de coleccionista" },
                    { Rarity.HGPR, "Raro paralelo holográfico" },
                    { Rarity.KCC, "Común de la Corporación Kaiba" },
                    { Rarity.KCR, "Corporación Kaiba Raro" },
                    { Rarity.KCUR, "Kaiba Corporación Ultra Raro" },
                    { Rarity.GUR, "Oro raro" },
                    { Rarity.GScR, "Oro Secreto Raro" },
                    { Rarity.GGR, "Fantasma/Oro Raro" },
                    { Rarity.PGR, "Oro premium raro" },
                    { Rarity.MLR, "Milenio raro" },
                    { Rarity.MLSR, "Milenio Súper Raro" },
                    { Rarity.MLUR, "Milenio ultra raro" },
                    { Rarity.MLScR, "Secreto del milenio raro" },
                    { Rarity.MLGR, "Millenium Oro Raro" },
                    { Rarity.DNPR, "Duelo Terminal Normal Paralela Rara" },
                    { Rarity.DPC, "Duel Terminal Paralelo Común" },
                    { Rarity.DNRPR, "Duelo Terminal Normal Rara Paralela Rara" },
                    { Rarity.DRPR, "Duelo Terminal Rara Paralela Rara" },
                    { Rarity.DSPR, "Duelo Terminal Super Paralela Rara" },
                    { Rarity.DUPR, "Duel Terminal Ultra Paralelo Raro" },
                    { Rarity.DScPR, "Duel Terminal Secreto Paralelo Raro" },
                    { Rarity.RR, "Rush rara" },
                    { Rarity.GRR, "Fiebre del oro rara" },
                    { Rarity.ORR, "Sobre Rush Rara" },
                    { Rarity.SE, "Edición estándar" },
                    { Rarity._1E, "1ra edición" },
                    { Rarity.UE, "Edición ilimitada" },
                    { Rarity.LE, "Edición limitada" },
                    { Rarity.DT, "Edición de terminal de duelo" },
                    { Rarity.FR, "Rareza fija" },
                    { Rarity.Vc, "Tarjeta variante" },
                    { Rarity.OgP, "Impresión original" },
                    { Rarity.RP, "Réplica" },
                    { Rarity.Rp, "Reimprimir" },
                    { Rarity.OoP, "Fuera de impresión" },
                    { Rarity.GC, "Tarjeta Gigante" },
                    { Rarity.OP, "Apoderado Oficial" },
                    { Rarity.CT, "Topper de caja" },
                    { Rarity.OSP, "Promoción de gran tamaño" },
                    { Rarity.BAM, "Leyenda BAM" }
                }
            },
            {
                Language.fr, new Dictionary<Rarity, string>
                {
                    { Rarity.N, "Normale" },
                    { Rarity.C, "Commune" },
                    { Rarity.NR, "Normal Rare" },
                    { Rarity.SP, "Impression courte" },
                    { Rarity.SSP, "Impression super courte" },
                    { Rarity.HFR, "Holofil Rare" },
                    { Rarity.R, "Rare" },
                    { Rarity.SR, "Super rare" },
                    { Rarity.UR, "Ultra rare" },
                    { Rarity.URPR, "Rare de Pharaon" },
                    { Rarity.UtR, "Rare ultime" },
                    { Rarity.GR, "Fantôme rare" },
                    { Rarity.HGR, "Rare holographique" },
                    { Rarity.PIR, "Platine rare" },
                    { Rarity.StR, "Lumière des étoiles rare" },
                    { Rarity.ScR, "Secrète rare" },
                    { Rarity.PScR, "Secrète Prismatique Rare" },
                    { Rarity.EScR, "Très secret rare" },
                    { Rarity.PlScR, "Platine Secrète Rare" },
                    { Rarity.UScR, "Rare ultra secrète" },
                    { Rarity._20ScR, "20e secret rare" },
                    { Rarity.ScUR, "Secrète Ultra Rare" },
                    { Rarity._10000ScR, "10000 secrets rares" },
                    { Rarity.PR, "Parallèle Rare" },
                    { Rarity.NPR, "Normal Parallèle Rare" },
                    { Rarity.PC, "Commun parallèle" },
                    { Rarity.SPR, "Super Parallèle Rare" },
                    { Rarity.UPR, "Ultra Parallèle Rare" },
                    { Rarity.ScPR, "Secret Parallèle Rare" },
                    { Rarity.EScPR, "Parallèle Extra Secret Rare" },
                    { Rarity.SFR, "Starfoil Rare" },
                    { Rarity.MSR, "Mosaïque Rare" },
                    { Rarity.SHR, "Brisefeuille Rare" },
                    { Rarity.CR, "Rare de collection" },
                    { Rarity.HGPR, "Holographique Parallèle Rare" },
                    { Rarity.KCC, "Commune de Kaiba Corporation" },
                    { Rarity.KCR, "Kaiba Corporation Rare" },
                    { Rarity.KCUR, "Kaiba Corporation Ultra Rare" },
                    { Rarity.GUR, "Or rares" },
                    { Rarity.GScR, "Or secret rare" },
                    { Rarity.GGR, "Fantôme/Or Rare" },
                    { Rarity.PGR, "Or premium rare" },
                    { Rarity.MLR, "Rare millénaire" },
                    { Rarity.MLSR, "Millénium Super Rare" },
                    { Rarity.MLUR, "Millenium Ultra Rare" },
                    { Rarity.MLScR, "Millenium secret rare" },
                    { Rarity.MLGR, "Millenium Or Rare" },
                    { Rarity.DNPR, "Duel Terminal Normal Parallèle Rare" },
                    { Rarity.DPC, "Duel Terminal Parallèle Commun" },
                    { Rarity.DNRPR, "Duel Terminal Normal Rare Parallèle Rare" },
                    { Rarity.DRPR, "Duel Terminal Rare Parallèle Rare" },
                    { Rarity.DSPR, "Duel Terminal Super Parallèle Rare" },
                    { Rarity.DUPR, "Duel Terminal Ultra Parallèle Rare" },
                    { Rarity.DScPR, "Duel Terminal Secret Parallèle Rare" },
                    { Rarity.RR, "Ruée rare" },
                    { Rarity.GRR, "Ruée vers l'or rare" },
                    { Rarity.ORR, "Plus de Rush Rare" },
                    { Rarity.SE, "Édition standard" },
                    { Rarity._1E, "1ère édition" },
                    { Rarity.UE, "Édition illimitée" },
                    { Rarity.LE, "Édition limitée" },
                    { Rarity.DT, "Duel Édition Terminal" },
                    { Rarity.FR, "Rareté fixe" },
                    { Rarity.Vc, "Carte variante" },
                    { Rarity.OgP, "Impression originale" },
                    { Rarity.RP, "Réplique" },
                    { Rarity.Rp, "Réimpression" },
                    { Rarity.OoP, "Épuisé" },
                    { Rarity.GC, "Carte géante" },
                    { Rarity.OP, "Mandataire officiel" },
                    { Rarity.CT, "Surmatelas" },
                    { Rarity.OSP, "Promo surdimensionnée" },
                    { Rarity.BAM, "Légende BAM" }
                }
            },
            {
                Language.it, new Dictionary<Rarity, string>
                {
                    { Rarity.N, "Normale" },
                    { Rarity.C, "Comune" },
                    { Rarity.NR, "Normale Raro" },
                    { Rarity.SP, "Stampa corta" },
                    { Rarity.SSP, "Stampa super corta" },
                    { Rarity.HFR, "Foglio olografico raro" },
                    { Rarity.R, "Rara" },
                    { Rarity.SR, "Super raro" },
                    { Rarity.UR, "Estremamente raro" },
                    { Rarity.URPR, "Raro del Faraone" },
                    { Rarity.UtR, "Ultimo raro" },
                    { Rarity.GR, "Fantasma raro" },
                    { Rarity.HGR, "Olografica rara" },
                    { Rarity.PIR, "Platino raro" },
                    { Rarity.StR, "Starlight raro" },
                    { Rarity.ScR, "Segreto raro" },
                    { Rarity.PScR, "Prismatico Segreto Raro" },
                    { Rarity.EScR, "Extra Segreto Raro" },
                    { Rarity.PlScR, "Platinum Secret Raro" },
                    { Rarity.UScR, "Ultra Segreto Raro" },
                    { Rarity._20ScR, "20° segreto raro" },
                    { Rarity.ScUR, "Segreto ultra raro" },
                    { Rarity._10000ScR, "10000 Segreti Rari" },
                    { Rarity.PR, "Parallelo Raro" },
                    { Rarity.NPR, "Normale Parallelo Raro" },
                    { Rarity.PC, "Comune parallelo" },
                    { Rarity.SPR, "Super Parallelo Raro" },
                    { Rarity.UPR, "Ultra Parallelo Raro" },
                    { Rarity.ScPR, "Segreto Parallelo Raro" },
                    { Rarity.EScPR, "Parallelo Segreto Extra Raro" },
                    { Rarity.SFR, "Starfoil Raro" },
                    { Rarity.MSR, "Mosaico raro" },
                    { Rarity.SHR, "Infrangibile raro" },
                    { Rarity.CR, "Raro da collezione" },
                    { Rarity.HGPR, "Olografico Parallelo Raro" },
                    { Rarity.KCC, "Comune di Kaiba Corporation" },
                    { Rarity.KCR, "Kaiba Corporation Raro" },
                    { Rarity.KCUR, "Kaiba Corporation Ultra Raro" },
                    { Rarity.GUR, "Oro raro" },
                    { Rarity.GScR, "Segreto d'oro raro" },
                    { Rarity.GGR, "Fantasma/Oro Raro" },
                    { Rarity.PGR, "Premium Gold Raro" },
                    { Rarity.MLR, "Millennio raro" },
                    { Rarity.MLSR, "Millennium super raro" },
                    { Rarity.MLUR, "Millennium ultra raro" },
                    { Rarity.MLScR, "Millennium Secret Raro" },
                    { Rarity.MLGR, "Millennium Gold raro" },
                    { Rarity.DNPR, "Duel Terminal Normale Parallelo Raro" },
                    { Rarity.DPC, "Duel Terminal Parallelo Comune" },
                    { Rarity.DNRPR, "Duello Terminale Normale Raro Parallelo Raro" },
                    { Rarity.DRPR, "Duel Terminal Raro Parallelo Raro" },
                    { Rarity.DSPR, "Duel Terminal Super Parallel Raro" },
                    { Rarity.DUPR, "Duel Terminal Ultra Parallelo Raro" },
                    { Rarity.DScPR, "Duel Terminal Segreto Parallelo Raro" },
                    { Rarity.RR, "Corsa rara" },
                    { Rarity.GRR, "Corsa all'oro rara" },
                    { Rarity.ORR, "Over Rush Raro" },
                    { Rarity.SE, "Edizione standard" },
                    { Rarity._1E, "1a edizione" },
                    { Rarity.UE, "Edizione illimitata" },
                    { Rarity.LE, "Edizione limitata" },
                    { Rarity.DT, "Edizione Duel Terminal" },
                    { Rarity.FR, "Rarità fissa" },
                    { Rarity.Vc, "Carta variante" },
                    { Rarity.OgP, "Stampa originale" },
                    { Rarity.RP, "Replica" },
                    { Rarity.Rp, "Ristampare" },
                    { Rarity.OoP, "Fuori stampa" },
                    { Rarity.GC, "Carta Gigante" },
                    { Rarity.OP, "Procura ufficiale" },
                    { Rarity.CT, "Caso topper" },
                    { Rarity.OSP, "Promo fuori misura" },
                    { Rarity.BAM, "Leggenda BAM" }
                }
            },
            {
                Language.ja, new Dictionary<Rarity, string>
                {
                    { Rarity.N, "普通" },
                    { Rarity.C, "一般" },
                    { Rarity.NR, "ノーマルレア" },
                    { Rarity.SP, "ショートプリント" },
                    { Rarity.SSP, "スーパーショートプリント" },
                    { Rarity.HFR, "ホロフォイルレア" },
                    { Rarity.R, "レア" },
                    { Rarity.SR, "スーパーレア" },
                    { Rarity.UR, "ウルトラ・レア" },
                    { Rarity.URPR, "ファラオのレア" },
                    { Rarity.UtR, "アルティメットレア" },
                    { Rarity.GR, "ゴーストレア" },
                    { Rarity.HGR, "ホログラフィックレア" },
                    { Rarity.PIR, "プラチナレア" },
                    { Rarity.StR, "スターライトレア" },
                    { Rarity.ScR, "シークレットレア" },
                    { Rarity.PScR, "プリズマティックシークレットレア" },
                    { Rarity.EScR, "エクストラシークレットレア" },
                    { Rarity.PlScR, "プラチナシークレットレア" },
                    { Rarity.UScR, "ウルトラシークレットレア" },
                    { Rarity._20ScR, "20thシークレットレア" },
                    { Rarity.ScUR, "シークレットウルトラレア" },
                    { Rarity._10000ScR, "10000シークレットレア" },
                    { Rarity.PR, "パラレルレア" },
                    { Rarity.NPR, "ノーマルパラレルレア" },
                    { Rarity.PC, "パラレルコモン" },
                    { Rarity.SPR, "スーパーパラレルレア" },
                    { Rarity.UPR, "ウルトラパラレルレア" },
                    { Rarity.ScPR, "シークレットパラレルレア" },
                    { Rarity.EScPR, "エクストラシークレット パラレルレア" },
                    { Rarity.SFR, "スターフォイルレア" },
                    { Rarity.MSR, "モザイクレア" },
                    { Rarity.SHR, "シャッターフォイルレア" },
                    { Rarity.CR, "コレクターズレア" },
                    { Rarity.HGPR, "ホログラフィックパラレルレア" },
                    { Rarity.KCC, "海馬コーポレーションコモン" },
                    { Rarity.KCR, "海馬コーポレーションレア" },
                    { Rarity.KCUR, "海馬コーポレーション ウルトラレア" },
                    { Rarity.GUR, "ゴールドレア" },
                    { Rarity.GScR, "ゴールドシークレットレア" },
                    { Rarity.GGR, "ゴースト/ゴールドレア" },
                    { Rarity.PGR, "プレミアムゴールドレア" },
                    { Rarity.MLR, "ミレニアムレア" },
                    { Rarity.MLSR, "ミレニアム スーパーレア" },
                    { Rarity.MLUR, "ミレニアム ウルトラレア" },
                    { Rarity.MLScR, "ミレニアム シークレット レア" },
                    { Rarity.MLGR, "ミレニアムゴールドレア" },
                    { Rarity.DNPR, "デュエルターミナル ノーマルパラレルレア" },
                    { Rarity.DPC, "デュエルターミナル パラレルコモン" },
                    { Rarity.DNRPR, "デュエルターミナル ノーマルレア パラレルレア" },
                    { Rarity.DRPR, "デュエルターミナルレア パラレルレア" },
                    { Rarity.DSPR, "デュエルターミナル スーパーパラレルレア" },
                    { Rarity.DUPR, "デュエルターミナル ウルトラパラレルレア" },
                    { Rarity.DScPR, "デュエルターミナル シークレット パラレルレア" },
                    { Rarity.RR, "ラッシュレア" },
                    { Rarity.GRR, "ゴールドラッシュレア" },
                    { Rarity.ORR, "オーバーラッシュレア" },
                    { Rarity.SE, "標準版" },
                    { Rarity._1E, "初版" },
                    { Rarity.UE, "アンリミテッド エディション" },
                    { Rarity.LE, "限定版" },
                    { Rarity.DT, "デュエルターミナルエディション" },
                    { Rarity.FR, "固定レアリティ" },
                    { Rarity.Vc, "バリアントカード" },
                    { Rarity.OgP, "オリジナルプリント" },
                    { Rarity.RP, "レプリカ" },
                    { Rarity.Rp, "再版" },
                    { Rarity.OoP, "絶版になって" },
                    { Rarity.GC, "ジャイアントカード" },
                    { Rarity.OP, "公式プロキシ" },
                    { Rarity.CT, "ケーストッパー" },
                    { Rarity.OSP, "特大プロモーション" },
                    { Rarity.BAM, "BAMレジェンド" }
                }
            },
            {
                Language.ko, new Dictionary<Rarity, string>
                {
                    { Rarity.N, "정상" },
                    { Rarity.C, "흔한" },
                    { Rarity.NR, "노멀 레어" },
                    { Rarity.SP, "짧은 인쇄" },
                    { Rarity.SSP, "슈퍼 쇼트 프린트" },
                    { Rarity.HFR, "홀로포일 희귀" },
                    { Rarity.R, "희귀한" },
                    { Rarity.SR, "슈퍼 레어" },
                    { Rarity.UR, "울트라 레어" },
                    { Rarity.URPR, "파라오의 희귀" },
                    { Rarity.UtR, "얼티밋 레어" },
                    { Rarity.GR, "고스트 레어" },
                    { Rarity.HGR, "홀로그램 희귀" },
                    { Rarity.PIR, "플래티넘 레어" },
                    { Rarity.StR, "별빛 희귀" },
                    { Rarity.ScR, "시크릿 레어" },
                    { Rarity.PScR, "분광 비밀 희귀" },
                    { Rarity.EScR, "엑스트라 시크릿 레어" },
                    { Rarity.PlScR, "플래티넘 시크릿 레어" },
                    { Rarity.UScR, "울트라 시크릿 레어" },
                    { Rarity._20ScR, "20번째 시크릿 레어" },
                    { Rarity.ScUR, "비밀 울트라 레어" },
                    { Rarity._10000ScR, "10000 시크릿 레어" },
                    { Rarity.PR, "병렬 희귀" },
                    { Rarity.NPR, "노멀 패러렐 레어" },
                    { Rarity.PC, "병렬 공통" },
                    { Rarity.SPR, "슈퍼 병렬 희귀" },
                    { Rarity.UPR, "울트라 패러렐 레어" },
                    { Rarity.ScPR, "시크릿 패러럴 레어" },
                    { Rarity.EScPR, "엑스트라 시크릿 패러럴 레어" },
                    { Rarity.SFR, "스타포일 희귀" },
                    { Rarity.MSR, "모자이크 레어" },
                    { Rarity.SHR, "샤터포일 희귀" },
                    { Rarity.CR, "수집가의 희귀" },
                    { Rarity.HGPR, "홀로그램 병렬 희귀" },
                    { Rarity.KCC, "카이바 주식회사 커먼" },
                    { Rarity.KCR, "카이바 코퍼레이션 레어" },
                    { Rarity.KCUR, "카이바 코퍼레이션 울트라 레어" },
                    { Rarity.GUR, "골드 레어" },
                    { Rarity.GScR, "골드 시크릿 레어" },
                    { Rarity.GGR, "고스트/골드 레어" },
                    { Rarity.PGR, "프리미엄 골드 레어" },
                    { Rarity.MLR, "밀레니엄 레어" },
                    { Rarity.MLSR, "밀레니엄 슈퍼 레어" },
                    { Rarity.MLUR, "밀레니엄 울트라 레어" },
                    { Rarity.MLScR, "밀레니엄 시크릿 레어" },
                    { Rarity.MLGR, "밀레니엄 골드 레어" },
                    { Rarity.DNPR, "듀얼 터미널 노멀 패러럴 레어" },
                    { Rarity.DPC, "듀얼 터미널 병렬 공통" },
                    { Rarity.DNRPR, "듀얼 터미널 노멀 레어 패러럴 레어" },
                    { Rarity.DRPR, "듀얼 터미널 레어 패러럴 레어" },
                    { Rarity.DSPR, "듀얼 터미널 슈퍼 패러럴 레어" },
                    { Rarity.DUPR, "듀얼 터미널 울트라 패러럴 레어" },
                    { Rarity.DScPR, "듀얼 터미널 시크릿 패러럴 레어" },
                    { Rarity.RR, "러쉬 레어" },
                    { Rarity.GRR, "골드 러시 희귀" },
                    { Rarity.ORR, "오버 러시 희귀" },
                    { Rarity.SE, "스탠다드 에디션" },
                    { Rarity._1E, "초판" },
                    { Rarity.UE, "무제한 에디션" },
                    { Rarity.LE, "한정판" },
                    { Rarity.DT, "듀얼 터미널 에디션" },
                    { Rarity.FR, "고정 희귀도" },
                    { Rarity.Vc, "변형 카드" },
                    { Rarity.OgP, "원본 인쇄" },
                    { Rarity.RP, "레플리카" },
                    { Rarity.Rp, "재판" },
                    { Rarity.OoP, "절판" },
                    { Rarity.GC, "자이언트 카드" },
                    { Rarity.OP, "공식 프록시" },
                    { Rarity.CT, "케이스 토퍼" },
                    { Rarity.OSP, "특대 프로모션" },
                    { Rarity.BAM, "BAM 레전드" }
                }
            },
            {
                Language.pt, new Dictionary<Rarity, string>
                {
                    { Rarity.N, "Normal" },
                    { Rarity.C, "Comum" },
                    { Rarity.NR, "Normal Raro" },
                    { Rarity.SP, "Impressão curta" },
                    { Rarity.SSP, "Impressão super curta" },
                    { Rarity.HFR, "Holofólio Raro" },
                    { Rarity.R, "Crua" },
                    { Rarity.SR, "Super raro" },
                    { Rarity.UR, "Ultra raro" },
                    { Rarity.URPR, "Raro do Faraó" },
                    { Rarity.UtR, "Raro Supremo" },
                    { Rarity.GR, "Fantasma Raro" },
                    { Rarity.HGR, "Raro holográfico" },
                    { Rarity.PIR, "Platina Raro" },
                    { Rarity.StR, "Starlight Raro" },
                    { Rarity.ScR, "Segredo Raro" },
                    { Rarity.PScR, "Segredo Prismático Raro" },
                    { Rarity.EScR, "Extra Segredo Raro" },
                    { Rarity.PlScR, "Segredo de Platina Raro" },
                    { Rarity.UScR, "Ultra Secreto Raro" },
                    { Rarity._20ScR, "20º Segredo Raro" },
                    { Rarity.ScUR, "Segredo Ultra Raro" },
                    { Rarity._10000ScR, "10000 Segredo Raro" },
                    { Rarity.PR, "Paralelo Raro" },
                    { Rarity.NPR, "Normal Paralelo Raro" },
                    { Rarity.PC, "Paralelo Comum" },
                    { Rarity.SPR, "Super Paralelo Raro" },
                    { Rarity.UPR, "Ultra Paralelo Raro" },
                    { Rarity.ScPR, "Segredo Paralelo Raro" },
                    { Rarity.EScPR, "Extra Secreto Paralelo Raro" },
                    { Rarity.SFR, "Starfoil Raro" },
                    { Rarity.MSR, "Mosaico Raro" },
                    { Rarity.SHR, "Shatterfoil Raro" },
                    { Rarity.CR, "Raro de colecionador" },
                    { Rarity.HGPR, "Paralelo Holográfico Raro" },
                    { Rarity.KCC, "Kaiba Corporation Common" },
                    { Rarity.KCR, "Kaiba Corporation Raro" },
                    { Rarity.KCUR, "Kaiba Corporation Ultra Raro" },
                    { Rarity.GUR, "Ouro Raro" },
                    { Rarity.GScR, "Segredo de Ouro Raro" },
                    { Rarity.GGR, "Fantasma/Ouro Raro" },
                    { Rarity.PGR, "Ouro Premium Raro" },
                    { Rarity.MLR, "Milênio Raro" },
                    { Rarity.MLSR, "Millennium Super Raro" },
                    { Rarity.MLUR, "Millennium Ultra Raro" },
                    { Rarity.MLScR, "Segredo do Milênio Raro" },
                    { Rarity.MLGR, "Milênio Ouro Raro" },
                    { Rarity.DNPR, "Duelo Terminal Normal Paralelo Raro" },
                    { Rarity.DPC, "Duel Terminal Paralelo Comum" },
                    { Rarity.DNRPR, "Duelo Terminal Normal Raro Paralelo Raro" },
                    { Rarity.DRPR, "Duel Terminal Raro Paralelo Raro" },
                    { Rarity.DSPR, "Duel Terminal Super Paralelo Raro" },
                    { Rarity.DUPR, "Duel Terminal Ultra Paralelo Raro" },
                    { Rarity.DScPR, "Duel Terminal Secret Paralelo Raro" },
                    { Rarity.RR, "Rush Raro" },
                    { Rarity.GRR, "Corrida do Ouro Raro" },
                    { Rarity.ORR, "Mais de Rush Raro" },
                    { Rarity.SE, "Edição Padrão" },
                    { Rarity._1E, "1ª edição" },
                    { Rarity.UE, "Edição Ilimitada" },
                    { Rarity.LE, "Edição limitada" },
                    { Rarity.DT, "Duel Terminal Edition" },
                    { Rarity.FR, "Raridade Fixa" },
                    { Rarity.Vc, "Cartão variante" },
                    { Rarity.OgP, "Impressão original" },
                    { Rarity.RP, "Réplica" },
                    { Rarity.Rp, "Reimprimir" },
                    { Rarity.OoP, "Fora de impressão" },
                    { Rarity.GC, "Cartão Gigante" },
                    { Rarity.OP, "Procuração oficial" },
                    { Rarity.CT, "Tampa da Caixa" },
                    { Rarity.OSP, "Promoção superdimensionada" },
                    { Rarity.BAM, "Legenda BAM" }
                }
            },
            {
                Language.zh, new Dictionary<Rarity, string>
                {
                    { Rarity.N, "普通的" },
                    { Rarity.C, "常见的" },
                    { Rarity.NR, "普通 稀有" },
                    { Rarity.SP, "短版印刷" },
                    { Rarity.SSP, "超短版印刷" },
                    { Rarity.HFR, "罕见的全息图" },
                    { Rarity.R, "稀有的" },
                    { Rarity.SR, "超级稀有" },
                    { Rarity.UR, "超稀有" },
                    { Rarity.URPR, "法老的稀有" },
                    { Rarity.UtR, "终极稀有" },
                    { Rarity.GR, "幽灵稀有" },
                    { Rarity.HGR, "全息稀有" },
                    { Rarity.PIR, "稀有铂金" },
                    { Rarity.StR, "星光稀有" },
                    { Rarity.ScR, "秘密稀有" },
                    { Rarity.PScR, "棱镜秘密 稀有" },
                    { Rarity.EScR, "额外的秘密稀有" },
                    { Rarity.PlScR, "白金秘密稀有" },
                    { Rarity.UScR, "超秘密稀有" },
                    { Rarity._20ScR, "第20个秘密稀有" },
                    { Rarity.ScUR, "秘密超稀有" },
                    { Rarity._10000ScR, "10000 秘密稀有" },
                    { Rarity.PR, "平行稀有" },
                    { Rarity.NPR, "普通平行稀有" },
                    { Rarity.PC, "并行公共" },
                    { Rarity.SPR, "超平行稀有" },
                    { Rarity.UPR, "超平行稀有" },
                    { Rarity.ScPR, "秘密平行稀有" },
                    { Rarity.EScPR, "额外的秘密平行稀有" },
                    { Rarity.SFR, "海星稀有" },
                    { Rarity.MSR, "马赛克稀有" },
                    { Rarity.SHR, "碎箔稀有" },
                    { Rarity.CR, "珍藏珍品" },
                    { Rarity.HGPR, "全息平行稀有" },
                    { Rarity.KCC, "海马公司 共同" },
                    { Rarity.KCR, "海马公司 稀有" },
                    { Rarity.KCUR, "海马公司超稀有" },
                    { Rarity.GUR, "黄金稀有" },
                    { Rarity.GScR, "黄金秘密稀有" },
                    { Rarity.GGR, "幽灵/黄金稀有" },
                    { Rarity.PGR, "优质黄金稀有" },
                    { Rarity.MLR, "千年珍稀" },
                    { Rarity.MLSR, "千年超稀有" },
                    { Rarity.MLUR, "千年超稀有" },
                    { Rarity.MLScR, "千年秘宝" },
                    { Rarity.MLGR, "千禧黄金稀有" },
                    { Rarity.DNPR, "决斗终端 普通 平行 稀有" },
                    { Rarity.DPC, "决斗终端并行通用" },
                    { Rarity.DNRPR, "决斗终端 普通 稀有 平行 稀有" },
                    { Rarity.DRPR, "决斗终端 稀有 平行 稀有" },
                    { Rarity.DSPR, "决斗终端超级平行稀有" },
                    { Rarity.DUPR, "决斗终端超平行稀有" },
                    { Rarity.DScPR, "决斗终端秘密平行稀有" },
                    { Rarity.RR, "拉什稀有" },
                    { Rarity.GRR, "淘金热 稀有" },
                    { Rarity.ORR, "过冲稀有" },
                    { Rarity.SE, "标准版" },
                    { Rarity._1E, "第 1 版" },
                    { Rarity.UE, "无限版" },
                    { Rarity.LE, "限量版" },
                    { Rarity.DT, "决斗终端版" },
                    { Rarity.FR, "固定稀有度" },
                    { Rarity.Vc, "变体卡" },
                    { Rarity.OgP, "原始打印" },
                    { Rarity.RP, "复制品" },
                    { Rarity.Rp, "重印" },
                    { Rarity.OoP, "绝版" },
                    { Rarity.GC, "巨卡" },
                    { Rarity.OP, "官方代理" },
                    { Rarity.CT, "案例礼帽" },
                    { Rarity.OSP, "超大促销" },
                    { Rarity.BAM, "巴姆传奇" }
                }
            }
        }
    );
}